### ISSUE TITLE
VirtualBox 5.2 support

### ISSUE THREAD

**Issue by Nikolas-500** [Delta2Force/MCVmComputers#174]
The VirtualBox 5.2 support will be useful for x86 computers and computers that doesn't support Virtualization Technology or computer owners who have Virtualization Technology off and doesn't know how to eneble it

**Comment by pivinx1** [comment]
Internet tutorials exist so turning on VT-x shouldn't be a problem, also using x86 for virtualization is well, a dumb idea since normally x86 CPUs support up to 3 GB of RAM unless PAE/NX is available, also at this point x86 based computers are practically nonexistent, thus adding x86 support would be pointless.

**Comment by vovaluzan** [comment]
all cpu before athlon 64 supports 64 bit instructions, all cpu before ~core 2 quad supports VT-X, and 6.* virtualbox supports no virtualization mode, but it slooow, and not support os before win 8

**Comment by prolexgreen** [comment]
clearly its not pointless because he asked for it i would like x86

**Comment by pivinx1** [comment]
From an resource standpoint, (PC resources I mean) on an x86 CPU without Physical Address Extension (PAE for short) getting Minecraft, the OS and the VM together might be a hard deal, since if you would assign 3 GB of RAM for Minecraft (that's just a gigabyte shy from the minimum amount of RAM that MC should be played on with mods) and if the max for an x86 PC is 4 GB, then about 128 MB remains for the VM and another ~512 MB for the OS (because 128 MB probably goes to hardware) , there is still kinda not enough for Windows/Linux/whatever to run on, so it's kinda dum unless your CPU can take PAE (just google it) allowing you to add more RAM.

> all cpu before athlon 64 supports 64 bit instructions, all cpu before ~core 2 quad supports VT-X, and 6.* virtualbox supports no virtualization mode, but it slooow, and not support os before win 8
I have no idea what are you talking about since it doesn't make sense, but when speaking about x64 for consumer PCs (I have left out Intel's Itanium which is like AMD's 64 bit arch, but it's rather pointed at workstations, datacenters and whatnot), rest of the CPUs that had 64bit were either on the PowerPC platform, or other platforms like SPARC or PA-RISC.
On the second argument, that's kind of true, since x86 virtualization was achieved in **1990**, but hardware virtualization wasn't out until 2005-2006, which means any CPU before these two dates couldn't support VT-x because it didn't exist yet.

Also, I think VBox 5 has a different API from VBox 6, which might be kinda hard to write again, it could probably be like porting it from Fabric to Forge but what do I know.
