### ISSUE TITLE
Make VM Computers based on Virtualbox 4.3.12

### ISSUE THREAD

**Issue by FredGamer** [Delta2Force/MCVmComputers#72]
Hello, I have a idea and storys. I downloaded and installed 5.2.xx version of Virtualbox, but... I got a error E_FAIL 0x80004005 and I have a Windows 7 SP1 32-bit. I tried all ways to fix it, but it's not works and I installed Virtualbox 4.3.12. And Errors E_FAIL 0x80004005 finally are gone on this stable version of Virtualbox. Please, make support older build of Virtualbox. I can't use it, I have 32-bit of Windows 7 and I can't install the 6.1 version of Virtualbox, I can't take it anymore...

**Comment by Delta2Force** [comment]
To be honest, I didn't even think that people were using 32-bit Computers anymore lol
Anyway, downgrading the API to 4.3 is pretty much impossible without fundamental changes to the code (which wouldn't make it work in 6.1.* anymore). You would have to clone it, change the library, remove all the imports from 6.1, replace all the code that wasn't in the API before, yadda yadda yadda.

**Comment by Meister1593** [comment]
@FredGamer There a possibility to use qemu in 32 bit OS, since it's not binded directly to code (except for program name)
But qemu implementation right now is very experimental and still has to be fixed (broken screens after relog (have to replace them each time), main issue rn)

**Comment by FredGamer** [comment]
@Meister1593 You make support for 4.3.12 version or I will close this issue.

**Comment by Meister1593** [comment]
> @Meister1593 You make support for 4.3.12 version or I will close this issue.

i don't really have much time to invest into this project right now, and i'm not gonna re-learn everything from qemu to virtualbox, so you're free to close this issue. Maybe i will come to this later, but tbh i don't think supporting 32 bit today is a good idea.

Right now QEMU 64 bit works `fine`, and that issue with placing new screens was entirely because when i opened game in dev workspace, it was setting up new player name each time.

**Comment by FredGamer** [comment]
Do support for 4.3.12, I gonna close it. Dumb.
